### ISSUE TITLE
collect_named_entities skip over entities

### ISSUE THREAD

**Issue by JulienMBABD** [davidsbatista/NER-Evaluation#18]
For example: `collect_named_entities(['B-LOC', 'I-LOC'])` will return `[]`.

**Fix**: 
ner_eval.py L149: `if ent_type is not None and start_offset is not None and end_offset is None:`

**Comment by davidsbatista** [comment]
Hi @JulienMBABD thanks for opening a PR, could maybe just add a test for this example? that would make this PR complete.

Another thing, https://github.com/ivyleavedtoadflax/nervaluate it's a python package made by @ivyleavedtoadflax based on this code, it might be more accurate than this version.

**Comment by j-rossi-nl** [comment]
I'm the same person, only I was logged under a different username (PR is under j-rossi-nl username).
Will do for the test.
I see in https://github.com/ivyleavedtoadflax/nervaluate/pull/28#issue-409349811 that the same exact fix has been offered already. Since it's my very first PR, I'll go through all the hoops nonetheless.

**Comment by davidsbatista** [comment]
@j-rossi-nl looks good, thanks for your contribution! :)

**Comment by davidsbatista** [comment]
PR merged

**Comment by ivyleavedtoadflax** [comment]
Also from me @j-rossi-nl  - I'm just implementing the fix in nervaluate finally
